-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 21:16:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SI_TESIS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SI_TESIS` ;

-- -----------------------------------------------------
-- Schema SI_TESIS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SI_TESIS` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema SI_TESIS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SI_TESIS` ;

-- -----------------------------------------------------
-- Schema SI_TESIS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SI_TESIS` DEFAULT CHARACTER SET utf8 ;
USE `SI_TESIS` ;

-- -----------------------------------------------------
-- Table `SI_TESIS`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SI_TESIS`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `codigo` INT NOT NULL,
  `correoInstitucional` VARCHAR(45) NOT NULL,
  `telefono` DECIMAL(10,0) NOT NULL,
  `rol` ENUM('ADMIN', 'USER') NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SI_TESIS`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SI_TESIS`.`Login` (
  `idLogin` INT UNSIGNED NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  CONSTRAINT `fk_Login_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `SI_TESIS`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idLogin_UNIQUE` ON `SI_TESIS`.`Login` (`idLogin` ASC) VISIBLE;

CREATE INDEX `fk_Login_Usuarios_idx` ON `SI_TESIS`.`Login` (`Usuarios_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SI_TESIS`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SI_TESIS`.`Proveedores` (
  `idProveedor` INT UNSIGNED NOT NULL,
  `tipoProveedoor` ENUM('NATURAL', 'EMPRESA') NOT NULL,
  `tipoIdentificacion` ENUM('RUT', 'NIT', 'CC') NOT NULL,
  `digito` INT NOT NULL,
  `nombreTitular` VARCHAR(45) NOT NULL,
  `nombreEmpresa` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `ubicacionContrato` VARCHAR(45) NULL,
  `fechaInicioContrato` DATETIME NULL,
  `fechaFinContrato` DATETIME NULL,
  `descripcionServicios` LONGTEXT NOT NULL,
  `activo` BIT(1) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProveedores_UNIQUE` ON `SI_TESIS`.`Proveedores` (`idProveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SI_TESIS`.`Acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SI_TESIS`.`Acciones` (
  `idAccion` INT NOT NULL,
  `accion` VARCHAR(45) NOT NULL,
  `estado` ENUM('RECHAZADO', 'APROBADO', 'PENDIENTE') NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `fechaAprobacion` DATETIME NOT NULL,
  `descripcionAccion` LONGTEXT NOT NULL,
  PRIMARY KEY (`idAccion`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idAcciones_Reporte_UNIQUE` ON `SI_TESIS`.`Acciones` (`idAccion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SI_TESIS`.`Reporte_Infraestructura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SI_TESIS`.`Reporte_Infraestructura` (
  `idReporte` INT UNSIGNED NOT NULL,
  `edificio` ENUM('PRINCIPE', 'VICTORIA', 'VILLA') NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `descripcionLugar` LONGTEXT NOT NULL,
  `tipoDanio` VARCHAR(45) NOT NULL,
  `descripcionDanio` LONGTEXT NOT NULL,
  `documentos` VARCHAR(45) NOT NULL,
  `token` INT NOT NULL,
  `estado` ENUM('RECHAZADO', 'APROBADO', 'SUPERVISION') NOT NULL,
  `tipoReporte` ENUM('INFRAESTRUCTURA', 'MANTENIMIENTO') NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `etapa` ENUM('EN PROCESO', 'TERMINADO', 'CANCELADO') NOT NULL,
  `ultimaModificacion` DATETIME NOT NULL,
  `Proveedores_idProveedor` INT UNSIGNED NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  `Acciones_idAccion` INT NOT NULL,
  PRIMARY KEY (`idReporte`),
  CONSTRAINT `fk_Reporte_Infraestructura_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `SI_TESIS`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Infraestructura_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `SI_TESIS`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Infraestructura_Acciones1`
    FOREIGN KEY (`Acciones_idAccion`)
    REFERENCES `SI_TESIS`.`Acciones` (`idAccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idResporte_UNIQUE` ON `SI_TESIS`.`Reporte_Infraestructura` (`idReporte` ASC) VISIBLE;

CREATE UNIQUE INDEX `token_UNIQUE` ON `SI_TESIS`.`Reporte_Infraestructura` (`token` ASC) VISIBLE;

CREATE INDEX `fk_Reporte_Infraestructura_Proveedores1_idx` ON `SI_TESIS`.`Reporte_Infraestructura` (`Proveedores_idProveedor` ASC) VISIBLE;

CREATE INDEX `fk_Reporte_Infraestructura_Usuarios1_idx` ON `SI_TESIS`.`Reporte_Infraestructura` (`Usuarios_idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Reporte_Infraestructura_Acciones1_idx` ON `SI_TESIS`.`Reporte_Infraestructura` (`Acciones_idAccion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SI_TESIS`.`Solicitud_Bienes_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SI_TESIS`.`Solicitud_Bienes_Servicios` (
  `idSolicitud` INT NOT NULL,
  `tipoSolicitud` ENUM('BIENES', 'SERVICIOS') NOT NULL,
  `productoSolicitado` VARCHAR(100) NOT NULL,
  `descripcionSolicitud` LONGTEXT NOT NULL,
  `fechaEntrega` DATETIME NOT NULL,
  `urgencia` ENUM('URGENTE', 'NOURGENTE') NOT NULL,
  `especificaciones` LONGTEXT NOT NULL,
  `Solicitud_Bienes_Servicioscol` VARCHAR(45) NOT NULL,
  `linksProducto` LONGTEXT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `ultimaModificacion` DATETIME NOT NULL,
  `Proveedores_idProveedor` INT UNSIGNED NOT NULL,
  `Acciones_idAccion` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSolicitud`),
  CONSTRAINT `fk_Solicitud_Bienes_Servicios_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `SI_TESIS`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_Bienes_Servicios_Acciones1`
    FOREIGN KEY (`Acciones_idAccion`)
    REFERENCES `SI_TESIS`.`Acciones` (`idAccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_Bienes_Servicios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `SI_TESIS`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idSolicitud_UNIQUE` ON `SI_TESIS`.`Solicitud_Bienes_Servicios` (`idSolicitud` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_Bienes_Servicios_Proveedores1_idx` ON `SI_TESIS`.`Solicitud_Bienes_Servicios` (`Proveedores_idProveedor` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_Bienes_Servicios_Acciones1_idx` ON `SI_TESIS`.`Solicitud_Bienes_Servicios` (`Acciones_idAccion` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_Bienes_Servicios_Usuarios1_idx` ON `SI_TESIS`.`Solicitud_Bienes_Servicios` (`Usuarios_idUsuario` ASC) VISIBLE;

USE `SI_TESIS` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
